// Organizational Structure Data
// Office, Bureau, Division, and Section definitions from actual DPSS organizational structure

export const organizationalData = {
    offices: [
        'Bureau of Human Resources',
        'Crossroads East',
        'Crossroads Main',
        'Crossroads West',
        'DPSS Academy',
        'Fiscal Management Division',
        'Fiscal Operations Division',
        'IHSS Crossroads',
        'Line Operation Division'
    ],
    bureaus: [
        'Bureau of Administrative Services',
        'Bureau of Customer Service Centers',
        'Bureau of Human Resources',
        'Bureau of Program & Policy',
        'Bureau of Special Operations',
        'Bureau of Technology Services',
        'Bureau of Workforce Services North',
        'Bureau of Workforce Services South',
        'DPSS Administration'
    ],
    divisions: [
        'AACES Division',
        'BAS Administration',
        'BPP Administration',
        'BSO Administration',
        'BWS North Administration',
        'BWS South Administration',
        'Bureau of Customer Service Centers Division',
        'Bureau of Human Resources Administration',
        'Bureau of Technology Services Administration',
        'CalWORKs & GAIN Program Division',
        'Chief Deputy Director',
        'Chief of Operations',
        'Communications & Project Management Division',
        'Contract Administration and Monitoring Division',
        'Contract Development Division',
        'Customer Service Center Division I',
        'Customer Service Center Division II',
        'Customer Service Center Division III',
        'Department Administration',
        'Financial Management Division',
        'Fiscal Operations Division',
        'General Relief & CalFresh Program Division',
        'General Services Division',
        'Human Capital Management Branch',
        'Human Relations Management Branch',
        'IHSS Operations Division',
        'Information Technology Services Division',
        'Medi-Cal / IHSS Program Division',
        'North Division I',
        'North Division II',
        'North Division III',
        'Program Compliance Division',
        'Research, Evaluation & Quality Assurance Division',
        'South Division I',
        'South Division II',
        'South Division III',
        'Special Assistant/Board Liaison',
        'Workforce Safety Leave & Disability Comp Branch'
    ],
    sections: [
        'Automation and Release Management',
        'BAS Administration Section',
        'BPP Administration Section',
        'BSO Administration Section',
        'BTS Administration',
        'BWS North Administration Section',
        'BWS South Administration Section',
        'Budget Planning & Control',
        'Budget Policy',
        'Benefit Recovery Accounting',
        'Bureau of Customer Service Centers Division Admin',
        'CalFresh Program Section I',
        'CalFresh Program Section II',
        'CalSAWs Project',
        'CalWORKs & GAIN Program Division Administration',
        'CalWORKs Program Section',
        'Chief Deputy Director Administration',
        'Chief of Operations Administration',
        'Child Care Program Section',
        'Civic Center',
        'Civil Rights',
        'Communications & Project Management Division Admin',
        'Communications Section',
        'Contract Administration and Monitoring Division Admin',
        'Contract Development Division Administration',
        'Cost Accounting & Revenue Management',
        'Contracts I',
        'Contracts II',
        'Contracts III',
        'Contracts IV',
        'Contracts V',
        'Contracts VI',
        'Customer Service Center Division I Administration',
        'Customer Service Center Division II Administration',
        'Customer Service Center Division III Administration',
        'Customer Service Center I - El Monte',
        'Customer Service Center II - La Cienega',
        'Customer Service Center IV',
        'Customer Service Center V',
        'Customer Service Center VI',
        'Customer Service Center VII',
        'Customer Service Center VIII',
        'DPSS Academy',
        'DPSS Administration Section',
        'DPSSTATS Section',
        'Discipline Policy and Litigation',
        'East Valley',
        'Emergency Safety and Security',
        'Field Technical Support',
        'Financial Management Division Administration',
        'Financial Special Projects and Revenue Management',
        'Fiscal Compliance',
        'Fiscal Intergrity & Compliance',
        'Fiscal Operations Division Administration',
        'Fund Management',
        'General Accounting',
        'GAIN Program Policy Section I',
        'GAIN Program Policy Section II',
        'GAIN Program Policy Section III',
        'GAIN Region III Pomona, sub',
        'GAIN Region III San Gabriel Valley Main',
        'GR & CF Division Administration',
        'GR Special Projects & SSI Advocacy Section',
        'GROW Program Section',
        'General Relief & CAPI Section',
        'General Services Division Administration',
        'Governmental Inquiry & Response',
        'HR Operations',
        'Health Care Reform Section',
        'Homeless Services Section',
        'Human Capital Management Administration',
        'Human Relations Management Administration',
        'Human Resources Administration Section',
        'IHSS Operations Division Administration',
        'IHSS Call Center Main - Industry',
        'IHSS Ops I Chatsworth',
        'IHSS Program',
        'Information Technology Security',
        'Intergovernmental Relations and CSBG Section',
        'Internal Affairs & Employee Relations',
        'Leave Management and Disability Compliance',
        'Line Operations and Integrated Services',
        'Long-Term LOA Section',
        'Management and Research Services',
        'Medi-Cal Program Section',
        'Medi-Cal LTC',
        'Medi-Cal/IHSS Program Division Administration',
        'Metro East',
        'North Division I Administration',
        'North Division II Administration',
        'North Division III Administration',
        'Norwalk',
        'Office Management',
        'PCD Line Operations Support',
        'Pomona',
        'Program Compliance Division Administration',
        'Project Management Office',
        'Property Management',
        'Recruitment & Position Management',
        'Renewal Line I',
        'Research, Evaluation & Quality Assurance Div Admin',
        'Security & Storage Management',
        'South Division I Administration',
        'South Division II Administration',
        'South Division III Administration',
        'South Family',
        'Special Asistant/Board Liaison Administration',
        'Technical Support',
        'Telecommunication & Electronic Document Management',
        'Warehouse Logistics & Asset Management',
        'Workforce Safety Leave & Disability Comp Admin'
    ]
};
//# sourceMappingURL=organizational-data.js.map